apiVersion: v1
kind: Secret
metadata:
  name: s18share-redis-auth
  namespace: s18share
type: Opaque
stringData:
  redis-password: "replace-me"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: s18share-redis-auth
  namespace: s18share
spec:
  secretTargetRef:
    - parameter: password
      name: s18share-redis-auth
      key: redis-password
