# Run Service - Executes agent runs; shared by the API router and Celery workers
import asyncio
import ast
import json
import logging
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, Optional

from shared.state import (
    active_loops,
    get_multi_mcp,
    get_remme_store,
    get_remme_extractor,
    PROJECT_ROOT,
)
from core.event_bus import event_bus
from core.run_store import get_run_store, merge_run_metadata
from core.skills.lifecycle import resolve_skill, run_skill_failure, run_skill_success
from core.supabase_logging import log_clinical_result, update_request_status
from remme.utils import get_embedding
from config.settings_loader import settings
from integrations.contracts import CanonicalRunRequest
from integrations.tenancy import storage_namespace_for_tenant

RUNS_INDEX_FILE = PROJECT_ROOT / "memory" / "runs.index.json"

logger = logging.getLogger(__name__)

class _LazyShared:
    def __init__(self, factory):
        self._factory = factory
        self._value = None

    def _get(self):
        if self._value is None:
            self._value = self._factory()
        return self._value

    def __getattr__(self, name):
        return getattr(self._get(), name)


# Keep service imports lightweight; heavy MCP/FAISS objects are created on first use.
multi_mcp = _LazyShared(get_multi_mcp)
remme_store = _LazyShared(get_remme_store)
remme_extractor = _LazyShared(get_remme_extractor)
run_store = get_run_store()


# === Background Tasks ===

def _infer_query_type(query: str) -> str:
    q = (query or "").lower()
    if "cbc" in q:
        return "cbc"
    if "rac" in q:
        return "rac"
    if "abdm" in q or "fhir" in q:
        return "abdm_fhir"
    if "mental_health" in q or "phq9" in q or "gad7" in q:
        return "mental_health"
    return "generic"


def _infer_query_type_from_canonical(canonical_request: CanonicalRunRequest) -> str:
    workflow_id = (canonical_request.workflow_id or "").strip().lower()
    if workflow_id and workflow_id != "generic":
        return workflow_id
    return _infer_query_type(canonical_request.query)


def _session_file_candidates(run_id: str, summaries_dir: Path):
    """
    Build likely session file locations for a run id.
    Run ids are usually epoch timestamps (ms precision), so we can map to the
    date-sharded path directly instead of scanning the whole tree.
    """
    filename = f"session_{run_id}.json"
    candidates = []

    # Fast path for default run ids generated by this service.
    if run_id.isdigit():
        ts_value = int(run_id)
        # 13+ digits => milliseconds, otherwise seconds.
        ts_seconds = ts_value / 1000.0 if len(run_id) >= 13 else float(ts_value)
        try:
            dt = datetime.fromtimestamp(ts_seconds)
            candidates.append(
                summaries_dir
                / f"{dt.year}"
                / f"{dt.month:02d}"
                / f"{dt.day:02d}"
                / filename
            )
        except (OverflowError, OSError, ValueError):
            pass

    # Compatibility fallback for custom/non-timestamp run ids.
    for path in summaries_dir.glob(f"**/{filename}"):
        candidates.append(path)

    return candidates


def _find_session_file(run_id: str, summaries_dir: Path) -> Optional[Path]:
    for candidate in _session_file_candidates(run_id, summaries_dir):
        if candidate.exists():
            return candidate
    return None


def _read_run_entry_sync(session_file: Path) -> Optional[Dict[str, Any]]:
    try:
        data = json.loads(session_file.read_text(encoding="utf-8", errors="ignore"))
        graph_details = data.get("graph", {})
        query = graph_details.get("original_query") or graph_details.get("globals", {}).get("original_query", "Unknown Query")
        created_at = graph_details.get("created_at") or datetime.fromtimestamp(session_file.stat().st_ctime).isoformat()
        nodes = data.get("nodes", [])
        node_statuses = [n.get("status", "pending") for n in nodes if n.get("id") != "ROOT"]
        if any(s == "running" for s in node_statuses):
            computed_status = "running"
        elif any(s == "failed" for s in node_statuses):
            computed_status = "failed"
        elif all(s == "completed" for s in node_statuses) and node_statuses:
            computed_status = "completed"
        else:
            computed_status = graph_details.get("status", "completed")
        total_tokens = sum((n.get("total_tokens", 0) or 0) for n in nodes)
        return {
            "id": session_file.stem.replace("session_", ""),
            "query": query,
            "created_at": created_at,
            "status": computed_status,
            "total_tokens": total_tokens,
            "path": str(session_file),
        }
    except Exception:
        return None


def _write_runs_index_sync(index_rows: list[Dict[str, Any]]) -> None:
    RUNS_INDEX_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = RUNS_INDEX_FILE.with_suffix(".json.tmp")
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(index_rows, fh, indent=2)
    tmp.replace(RUNS_INDEX_FILE)


async def _refresh_runs_index() -> list[Dict[str, Any]]:
    summaries_dir = PROJECT_ROOT / "memory" / "session_summaries_index"
    if not summaries_dir.exists():
        return []
    session_files = list(summaries_dir.glob("**/session_*.json"))
    rows = []
    for entry in await asyncio.gather(*[asyncio.to_thread(_read_run_entry_sync, path) for path in session_files]):
        if entry:
            rows.append(entry)
    rows.sort(key=lambda x: x["id"], reverse=True)
    await asyncio.to_thread(_write_runs_index_sync, rows)
    return rows


async def _load_runs_index() -> list[Dict[str, Any]]:
    if RUNS_INDEX_FILE.exists():
        try:
            data = await asyncio.to_thread(lambda: json.loads(RUNS_INDEX_FILE.read_text(encoding="utf-8")))
            if isinstance(data, list):
                return data
        except Exception:
            pass
    return await _refresh_runs_index()


def _normalize_run_status(raw_status: Optional[str]) -> str:
    status = (raw_status or "failed").strip().lower()
    if status == "success":
        return "completed"
    if status == "paused":
        return "stopped"
    if status not in {
        "accepted",
        "starting",
        "running",
        "waiting_input",
        "completed",
        "failed",
        "stopped",
        "interrupted",
    }:
        return "failed"
    return status


def _retrieve_memories_sync(query: str):
    return remme_store.search_text(query, limit=3, requester="run_context")


async def _build_memory_context(run_id: str, query: str):
    memory_context = ""
    results = []

    try:
        # Keep sync embedding/search work off the event loop so /runs polling
        # stays responsive under load.
        results = await asyncio.to_thread(_retrieve_memories_sync, query)
        if results:
            memory_str = "\n".join([f"- {r['text']} (Confidence: {r.get('score', 0):.2f})" for r in results])
            memory_context = f"PREVIOUS MEMORIES ABOUT USER:\n{memory_str}\n"
            logger.info("Remme: Injected %d memories into run %s", len(results), run_id)
    except Exception as e:
        logger.warning("Remme retrieval failed: %s", e)

    try:
        rag_result = await multi_mcp.call_tool("rag", "search_stored_documents_rag", {"query": query})
        if rag_result and hasattr(rag_result, "content") and isinstance(rag_result.content, list):
            snippets = []
            for item in rag_result.content:
                if hasattr(item, "text"):
                    try:
                        parsed = ast.literal_eval(item.text)
                        if isinstance(parsed, list):
                            snippets.extend(parsed[:5])
                        else:
                            snippets.append(item.text[:500])
                    except Exception:
                        snippets.append((item.text or "")[:500])
            if snippets:
                rag_str = "\n".join(f"- {s[:400]}..." if len(s) > 400 else f"- {s}" for s in snippets[:8])
                memory_context += f"\nRELEVANT DOCUMENT SNIPPETS (RAG):\n{rag_str}\n"
                logger.info("Injected %d RAG snippets into run context for %s", len(snippets), run_id)
    except Exception as e:
        logger.warning("RAG context injection failed (non-fatal): %s", e)

    return memory_context, results


async def _mirror_run_status_from_events(run_id: str, stop_signal: asyncio.Event):
    queue = await event_bus.subscribe(max_queue_size=500)
    try:
        while not stop_signal.is_set():
            try:
                event = await asyncio.wait_for(queue.get(), timeout=0.5)
            except asyncio.TimeoutError:
                continue

            data = event.get("data", {})
            if data.get("session_id") != run_id:
                continue

            event_type = event.get("type")
            if event_type == "run_started":
                await asyncio.to_thread(run_store.update_status, run_id, "running")
            elif event_type == "step_update":
                status = data.get("status")
                if status == "waiting_input":
                    await asyncio.to_thread(run_store.update_status, run_id, "waiting_input")
                elif status == "running":
                    await asyncio.to_thread(run_store.update_status, run_id, "running")
            elif event_type == "run_finished":
                status = _normalize_run_status(data.get("status"))
                await asyncio.to_thread(run_store.update_status, run_id, status)
                return
    finally:
        event_bus.unsubscribe(queue)


async def process_run(
    run_id: str,
    canonical_request: CanonicalRunRequest,
    audit_context: Optional[Dict[str, Any]] = None,
    tenant_context: Optional[Dict[str, str]] = None,
):
    """Background task to execute the agent loop"""
    skill = None
    resolved_skill_id: Optional[str] = None
    skill_result: Optional[Dict[str, Any]] = None
    query = canonical_request.query
    tenant_context = tenant_context or {
        "tenant_id": canonical_request.tenant_id,
        "tenant_tier": canonical_request.tenant_tier,
        "data_region": canonical_request.data_region or "in",
    }
    storage_namespace = storage_namespace_for_tenant(tenant_context, settings.get("tenancy", {}))
    final_result: Dict[str, Any] = {"status": "failed", "summary": "Run did not complete", "run_id": run_id}
    context = None
    results = []
    from core.loop import AgentLoop4

    loop = AgentLoop4(multi_mcp=multi_mcp)
    active_loops[run_id] = loop
    try:
        skill, query, resolved_skill_id = await resolve_skill(
            query=canonical_request.query,
            run_id=run_id,
            agent_id=canonical_request.workflow_id or "runs",
            explicit_skill_id=canonical_request.skill_id,
            integration_id=canonical_request.integration_id,
            workflow_id=canonical_request.workflow_id,
        )
    except Exception as e:
        logger.warning("Skill resolution failed for run %s: %s", run_id, e)
        skill = None
        resolved_skill_id = None
        query = canonical_request.query
    skill_source = None
    if resolved_skill_id:
        skill_source = "explicit" if canonical_request.skill_id else "intent"
        await asyncio.to_thread(
            merge_run_metadata,
            run_id,
            {"skill_id": resolved_skill_id, "skill_source": skill_source},
        )
    await asyncio.to_thread(
        run_store.update_status,
        run_id,
        "starting",
        query=canonical_request.query,
        integration_id=canonical_request.integration_id,
        workflow_id=canonical_request.workflow_id,
        tenant_id=canonical_request.tenant_id,
        tenant_tier=canonical_request.tenant_tier,
        data_region=canonical_request.data_region,
    )
    mirror_stop = asyncio.Event()
    mirror_task = asyncio.create_task(_mirror_run_status_from_events(run_id, mirror_stop))
    trace_token = multi_mcp.set_trace_context(
        {
            "integration_id": canonical_request.integration_id,
            "workflow_id": canonical_request.workflow_id,
            "contract_version": canonical_request.contract_version,
            "tenant_id": canonical_request.tenant_id,
            "tenant_tier": canonical_request.tenant_tier,
            "data_region": canonical_request.data_region,
            "storage_namespace": storage_namespace,
        }
    )
    try:
        # 1. RETRIEVE MEMORIES (Remme)
        # Search for past relevant facts to injecting into this run
        memory_context, results = await _build_memory_context(run_id, query)

        # Execute the loop
        # The loop will maintain its own internal context
        logger.info("[%s] MEMORY CONTEXT READY (%d chars)", run_id, len(memory_context))
        try:
             context = await loop.run(
                 query,
                 [],
                 {
                     "_integration_meta": {
                         "integration_id": canonical_request.integration_id,
                         "workflow_id": canonical_request.workflow_id,
                         "contract_version": canonical_request.contract_version,
                     }
                 },
                 [],
                 session_id=run_id,
                 memory_context=memory_context,
                 storage_namespace=storage_namespace,
             )
        except asyncio.CancelledError:
             logger.info("[%s] Run cancelled.", run_id)
             context = loop.context # Recovery context from loop if possible

        # 2. EXTRACT NEW MEMORIES (Remme)
        # We put this in a finally block? No, because we want it only on success/completion of meaningful work.
        # But if user stops it, we might want to extract partials.
        # For now, let's leave it after run() but handle the stop case explicitly if context is returned.
        
    except Exception as e:
        logger.error("Run %s failed: %s", run_id, e)
    finally:
        mirror_stop.set()
        if not mirror_task.done():
            mirror_task.cancel()
            try:
                await mirror_task
            except asyncio.CancelledError:
                pass
        multi_mcp.reset_trace_context(trace_token)
        # Clean up
        if run_id in active_loops:
            del active_loops[run_id]
            
        # Attempt extraction if we have context (even if stopped)
        # Note: 'context' variable needs to be accessible here.
        pass 
        # After run completes, extract new facts
        try:
            # Get the history from context (Plan Graph or Session Summary)
            # For now, we don't return the full conversation history from loop.run directly
            # But context has plan_graph... 
            # Ideally we extract from the "Summary" generated by the ReportingAgent if available
            # OR we can pass the query and the FINAL output.
            
            # Simple V1: Extract from Query + Final Answer (if available)
            final_output = ""
            # Try to find final output from graph
            if context and context.plan_graph:
                # Find nodes with output
                for node_id in context.plan_graph.nodes:
                    node = context.plan_graph.nodes[node_id]
                    if node.get("status") == "completed" and node.get("output"):
                        final_output += f"{node_id} Output: {str(node['output'])}\n"

            history = [{"role": "assistant", "content": final_output}]
            
            logger.info("Remme: Extracting facts from run %s...", run_id)
            # Pass existing memories from earlier search to context-aware extractor
            # ⚡ RUN IN THREAD TO AVOID BLOCKING EVENT LOOP
            commands, preferences = await asyncio.to_thread(
                remme_extractor.extract, 
                query, 
                history, 
                existing_memories=results
            )
            
            if commands:
                # Skip embedding work entirely once Ollama has failed on this
                # run - each failing call can block ~12 minutes (two endpoints
                # x OLLAMA_TIMEOUT). Fail fast and keep the event loop healthy.
                embedding_available = True
                for cmd in commands:
                    if not isinstance(cmd, dict):
                        logger.warning("Remme: Skipping invalid command format: %r", cmd)
                        continue

                    action = cmd.get("action")
                    text = cmd.get("text")
                    target_id = cmd.get("id")

                    try:
                        if action == "add" and text:
                            if not embedding_available:
                                continue
                            emb = await asyncio.to_thread(get_embedding, text, "search_document")
                            remme_store.add(text, emb, category="derived", source=f"run_{run_id}")
                            logger.info("Remme: Added new fact: %s", text)
                        elif action == "update" and target_id and text:
                            if not embedding_available:
                                continue
                            emb = await asyncio.to_thread(get_embedding, text, "search_document")
                            remme_store.update_text(target_id, text, emb, source=f"run_{run_id}")
                            logger.info("Remme: Updated fact %s: %s", target_id, text)
                        elif action == "delete" and target_id:
                            remme_store.delete(target_id, source=f"run_{run_id}")
                            logger.info("Remme: Deleted fact %s", target_id)
                    except RuntimeError as e:
                        # core.embedding raises RuntimeError when Ollama is
                        # unreachable. Trip the breaker so we don't pay the
                        # timeout again for the remaining commands.
                        embedding_available = False
                        logger.error("Remme Action Failed (embedding unavailable): %s", e)
                    except Exception as e:
                        logger.error("Remme Action Failed: %s", e)
            
            # Apply preferences to hubs
            if preferences:
                from remme.extractor import apply_preferences_to_hubs
                apply_preferences_to_hubs(preferences)
                logger.info("Remme: Processed %d preference updates.", len(preferences))

            if commands:
                logger.info("Remme: Processed %d memory updates.", len(commands))
            elif not preferences:
                logger.info("Remme: No new facts extracted from run %s.", run_id)

        except Exception as e:
            logger.error("Remme Extraction Failed: %s", e, exc_info=True)

        # 3. AUTO-SAVE REPORTS TO NOTES
            # 3. AUTO-SAVE REPORTS TO NOTES
        try:
             if context and context.plan_graph:
                import re
                
                notes_dir = PROJECT_ROOT / "data" / "Notes" / "Arcturus"
                notes_dir.mkdir(parents=True, exist_ok=True)
                
                def sanitize_filename(title):
                    title = re.sub(r'[\\/*?:"<>|#]', "", title)
                    title = title.replace("\n", " ").strip()
                    return title[:60].strip()

                def extract_title(content):
                    match = re.search(r'^#+\s+(.+)$', content, re.MULTILINE)
                    if match:
                        return match.group(1).strip()
                    # Fallback to first non-empty line
                    lines = [l.strip() for l in content.split('\n') if l.strip()]
                    if lines:
                        return lines[0]
                    return "Untitled Report"

                for node_id in context.plan_graph.nodes:
                    node = context.plan_graph.nodes[node_id]
                    output = node.get("output", {})
                    if not output: continue

                    # Check for Formatter output keys
                    markdown = output.get("markdown_report")
                    if not markdown:
                         for k, v in output.items():
                             if k.startswith("formatted_report") and isinstance(v, str):
                                 markdown = v
                                 break
                    
                    if markdown and len(markdown) > 100:
                         title = extract_title(markdown)
                         filename = sanitize_filename(title) + ".md"
                         target_path = notes_dir / filename
                         
                         if target_path.exists() and len(target_path.read_text(encoding='utf-8')) >= len(markdown):
                             continue

                         with open(target_path, 'w', encoding='utf-8') as f:
                             f.write(markdown)
                         logger.info("Auto-Saved Report to Notes: %s", filename)

        except Exception as e:
            logger.warning("Failed to auto-save report: %s", e)
            
        if context and context.plan_graph:
            # Derive status from the plan graph instead of optimistically flipping
            # to "completed". Mirrors the logic used in process_resume so a run
            # that was cancelled or crashed mid-flight is not reported as done.
            failed_node_id = None
            failed_error = None
            for node_id in context.plan_graph.nodes:
                node = context.plan_graph.nodes[node_id]
                if node.get("status") == "failed":
                    failed_node_id = node_id
                    failed_error = node.get("error")
                    break
            if failed_node_id is not None:
                final_result["status"] = "failed"
                final_result["run_id"] = run_id
                final_result["error"] = failed_error
            else:
                graph_status = context.plan_graph.graph.get("status")
                node_statuses = [
                    context.plan_graph.nodes[n].get("status", "pending")
                    for n in context.plan_graph.nodes
                    if n != "ROOT"
                ]
                if graph_status in {"completed", "failed", "paused", "stopped"}:
                    derived_status = graph_status
                elif node_statuses and all(s == "completed" for s in node_statuses):
                    derived_status = "completed"
                else:
                    # Partial / running / interrupted - keep as failed so the run
                    # does not masquerade as successful.
                    derived_status = "failed"
                final_result["status"] = derived_status
                final_result["run_id"] = run_id
        
        if context:
             try:
                 output_str = ""
                 if context.plan_graph:
                     # 1. Look for FormatterAgent output first (The Final Report)
                     for node_id in context.plan_graph.nodes:
                         node = context.plan_graph.nodes[node_id]
                         node_agent = node.get("agent", "")
                         out = node.get("output", {})
                         
                         if node_agent == "FormatterAgent" or "Format" in node_agent:
                             if isinstance(out, dict):
                                 md = out.get("markdown_report")
                                 if not md:
                                     # Try all keys for something that looks like a report
                                     for k, v in out.items():
                                         if (k.startswith("formatted_report") or k == "report") and isinstance(v, str):
                                             md = v
                                             break
                                 
                                 if md:
                                     output_str = md
                                     break
                                 
                                 # Fallback: if 'output' is a long string
                                 if isinstance(out.get("output"), str) and len(out["output"]) > 100:
                                     output_str = out["output"]
                                     break
                     
                     # 2. Fallback: Find any node with a substantial string output
                     if not output_str:
                         for node_id in reversed(list(context.plan_graph.nodes)):
                             if node_id == "ROOT": continue
                             node = context.plan_graph.nodes[node_id]
                             out = node.get("output", {})
                             
                             if isinstance(out, dict):
                                 # Try to find the largest string value in the dict (recursive search)
                                 def find_largest_string(d):
                                     largest = ""
                                     for v in d.values():
                                         if isinstance(v, str):
                                             if len(v) > len(largest):
                                                 largest = v
                                         elif isinstance(v, dict):
                                             sub = find_largest_string(v)
                                             if len(sub) > len(largest):
                                                 largest = sub
                                     return largest
                                 
                                 largest_str = find_largest_string(out)
                                 if len(largest_str) > 50:
                                     output_str = largest_str
                                     break
                                     
                             elif isinstance(out, str) and len(out) > 50:
                                 output_str = out
                                 break

                 # 3. RUTHLESS CLEANING: Remove typical JSON leakage if content is actually Markdown
                 if output_str:
                     import re
                     # If the output starts and ends with {} or [], it might be a JSON dump 
                     # that contains a markdown_report field.
                     if (output_str.startswith("{") and output_str.endswith("}")) or (output_str.startswith("[") and output_str.endswith("]")):
                         try:
                             # Try to parse it and extract the report field
                             data = json.loads(output_str)
                             if isinstance(data, dict):
                                 # Look for report-like keys
                                 for k in ["markdown_report", "formatted_report", "output", "summary", "report"]:
                                     if data.get(k) and isinstance(data[k], str) and len(data[k]) > 50:
                                         output_str = data[k]
                                         break
                         except (TypeError, ValueError):
                             pass
                     
                     # Final check: remove block delimiters if LLM wrapped them in ```markdown
                     output_str = re.sub(r'^```(?:markdown)?\n', '', output_str)
                     output_str = re.sub(r'\n```$', '', output_str)

                 final_result["output"] = output_str.strip() if output_str else "No substantial output found."
                 if final_result.get("status") == "failed":
                     final_result["summary"] = f"Failed: {final_result.get('error', 'Unknown error')}"
                 else:
                     final_result["summary"] = output_str.strip() if output_str else "Completed."
             except Exception as e:
                 logger.warning("Extraction Error: %s", e)

        try:
            artifact = {
                "status": final_result.get("status"),
                "summary": final_result.get("summary"),
                "output": final_result.get("output"),
                "error": final_result.get("error"),
            }
            if skill and final_result.get("status") == "failed":
                await run_skill_failure(skill, str(final_result.get("error") or "Run failed"))
            else:
                skill_result = await run_skill_success(skill, artifact)
                if skill_result:
                    final_result["skill"] = skill_result
                    if skill_result.get("summary"):
                        final_result["summary"] = skill_result["summary"]
        except Exception as e:
            logger.warning("Skill lifecycle hook failed for run %s: %s", run_id, e)
        
        if audit_context:
            try:
                final_status = final_result.get("status", "failed")
                error_code = final_result.get("error") if final_status == "failed" else None
                await update_request_status(
                    idempotency_key=audit_context["idempotency_key"],
                    run_id=run_id,
                    status=final_status,
                    error_code=error_code,
                )
                await log_clinical_result(
                    {
                        "run_id": run_id,
                        "request_id": audit_context.get("request_id"),
                        "idempotency_key": audit_context["idempotency_key"],
                        "query_type": _infer_query_type_from_canonical(canonical_request),
                        "normalized_result": {
                            "summary": final_result.get("summary"),
                            "output": final_result.get("output"),
                        },
                        "integration_id": canonical_request.integration_id,
                        "workflow_id": canonical_request.workflow_id,
                        "contract_version": canonical_request.contract_version,
                        "tenant_id": canonical_request.tenant_id,
                        "tenant_tier": canonical_request.tenant_tier,
                        "data_region": canonical_request.data_region,
                        "summary": final_result.get("summary"),
                        "triage_flag": "high" if final_status == "failed" else "normal",
                        "status": final_status,
                        "error_code": error_code,
                    }
                )
            except Exception as e:
                logger.warning("Supabase result logging failed for run %s: %s", run_id, e)
        try:
            await _refresh_runs_index()
        except Exception:
            logger.debug("Failed to refresh runs index for run %s", run_id, exc_info=True)

        await asyncio.to_thread(
            run_store.update_status,
            run_id,
            _normalize_run_status(final_result.get("status")),
            summary=final_result.get("summary"),
            error=final_result.get("error"),
        )
        if resolved_skill_id:
            await asyncio.to_thread(
                merge_run_metadata,
                run_id,
                {
                    "skill_id": resolved_skill_id,
                    "skill_source": skill_source,
                    "skill_result": skill_result,
                },
            )

        return final_result


async def process_resume(run_id: str, audit_context: Optional[Dict[str, Any]] = None):
    """Background task to resume a saved run from disk."""
    final_result: Dict[str, Any] = {"status": "failed", "summary": "Run did not complete", "run_id": run_id}
    context = None
    results = []
    query = ""
    from core.loop import AgentLoop4

    loop = AgentLoop4(multi_mcp=multi_mcp)
    active_loops[run_id] = loop
    await asyncio.to_thread(run_store.update_status, run_id, "starting")
    mirror_stop = asyncio.Event()
    mirror_task = asyncio.create_task(_mirror_run_status_from_events(run_id, mirror_stop))
    try:
        summaries_dir = PROJECT_ROOT / "memory" / "session_summaries_index"
        found_file = _find_session_file(run_id, summaries_dir)
        if not found_file:
            raise FileNotFoundError(f"Run {run_id} not found")

        data = await asyncio.to_thread(lambda: json.loads(found_file.read_text(encoding="utf-8", errors="ignore")))
        query = data.get("graph", {}).get("original_query") or ""
        memory_context = data.get("graph", {}).get("memory_context")
        if memory_context is None and query:
            memory_context, results = await _build_memory_context(run_id, query)

        context = await loop.resume(found_file, memory_context=memory_context)
    except Exception as e:
        logger.error("Resume %s failed: %s", run_id, e)
    finally:
        mirror_stop.set()
        if not mirror_task.done():
            mirror_task.cancel()
            try:
                await mirror_task
            except asyncio.CancelledError:
                pass
        if run_id in active_loops:
            del active_loops[run_id]

        if context and context.plan_graph:
            for node_id in context.plan_graph.nodes:
                node = context.plan_graph.nodes[node_id]
                if node.get("status") == "failed":
                    final_result["status"] = "failed"
                    final_result["error"] = node.get("error")
                    break
            else:
                final_result["status"] = context.plan_graph.graph.get("status", "completed")

        if audit_context:
            try:
                await update_request_status(
                    idempotency_key=audit_context["idempotency_key"],
                    run_id=run_id,
                    status=final_result.get("status", "failed"),
                    error_code=final_result.get("error"),
                )
                await log_clinical_result(
                    {
                        "run_id": run_id,
                        "request_id": audit_context.get("request_id"),
                        "idempotency_key": audit_context["idempotency_key"],
                        "query_type": _infer_query_type(query),
                        "normalized_result": {
                            "summary": final_result.get("summary"),
                            "output": final_result.get("output"),
                        },
                        "summary": final_result.get("summary"),
                        "triage_flag": "high" if final_result.get("status") == "failed" else "normal",
                        "status": final_result.get("status", "failed"),
                        "error_code": final_result.get("error"),
                        "event": "resume",
                    }
                )
            except Exception as e:
                logger.warning("Supabase resume logging failed for run %s: %s", run_id, e)
        try:
            await _refresh_runs_index()
        except Exception:
            logger.debug("Failed to refresh runs index for resumed run %s", run_id, exc_info=True)

        await asyncio.to_thread(
            run_store.update_status,
            run_id,
            _normalize_run_status(final_result.get("status")),
            summary=final_result.get("summary"),
            error=final_result.get("error"),
        )

        return final_result
